name: rtsh26-hackathon-backend

services:
  db:
    image: postgres:18.0-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d project_database"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
